[package]
name = "guest"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "1.1",default-features = false}
serde = { version = "1", default-features = false, features = ["derive"] }
sha2 = "0.10"

[build]
target = "riscv32im-risc0-zkvm-elf"
